# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [
      "nvidia"
      "nvidia_modeset"
      "nvidia_uvm"
      "nvidia_drm"
  ];
  boot.kernelModules = [ ];
  boot.kernelParams = [ "transparent_hugepage=never" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = "options nvidia-drm modeset=1";
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/10750885-8351-4941-9a71-768daad97c6e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2238170f-6791-4d2c-a64e-5dc7acece258".device = "/dev/disk/by-uuid/2238170f-6791-4d2c-a64e-5dc7acece258";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D66A-94F5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp82s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
