general.import = ["/home/arjen/.config/alacritty/catppuccin/catppuccin-machiatto.toml"]

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 15
y = 15
